// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Polgo_Products.Data;

#nullable disable

namespace Polgo_Products.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250326083413_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Polgo_Products.Models.Products", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.Property<string>("productName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            id = 1,
                            manufacturer = "",
                            price = 0.0,
                            productName = "Tapsilog",
                            type = "Rice"
                        },
                        new
                        {
                            id = 2,
                            manufacturer = "",
                            price = 0.0,
                            productName = "Carbonara",
                            type = "Spaghetti"
                        },
                        new
                        {
                            id = 3,
                            manufacturer = "",
                            price = 0.0,
                            productName = "Pancit Canton",
                            type = "Noodles"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
